- src/spaceone/inventory/service/collector_service.py
add garbage collections to google: compute_vm
> add garbage collections to google: compute_vm

- src/spaceone/inventory/manager/compute_engine/vm_instance_manager.py
- src/spaceone/inventory/service/collector_service.py
Update for minor updates image id
> Update for minor updates

- README.md
Add service account's authentication
> [CLOUD-3323] Add service account's authentication

- src/spaceone/inventory/manager/collector_manager.py
- src/spaceone/inventory/manager/compute_engine/vm_instance_manager.py
- src/spaceone/inventory/model/google_cloud.py
- src/spaceone/inventory/model/server.py
Update labels to tags due to standardization
> [CLOUD-3401] Update labels to tags due to standardization

- src/spaceone/inventory/model/metadata/metadata_dynamic_field.py
Update primary to violet.500 in dynamic field
> Update primary to violet.500 in dynamic field

- src/spaceone/inventory/connector/google_cloud_compute_connector.py
- src/spaceone/inventory/manager/collector_manager.py
- src/spaceone/inventory/manager/compute_engine/vm_instance_manager.py
- To diminish number of api calls
- collecting compute vms over Zone or regions
> [CLOUD-3814] Update for one-call API

- README.md
- stable version for compute vm
> Update for one-call API

- src/spaceone/inventory/connector/google_cloud_compute_connector.py
- src/spaceone/inventory/manager/collector_manager.py
- src/spaceone/inventory/manager/compute_engine/disk_manager.py
- src/spaceone/inventory/service/collector_service.py
- test/api/test_collector.py
bug fix for decimal digit for disk i/o
> bug fix for decimal digit for disk i/o

- src/spaceone/inventory/connector/google_cloud_compute_connector.py
- src/spaceone/inventory/manager/collector_manager.py
- src/spaceone/inventory/manager/compute_engine/disk_manager.py
- src/spaceone/inventory/manager/compute_engine/vm_instance_manager.py
- src/spaceone/inventory/manager/compute_engine/vpc_manager.py
- src/spaceone/inventory/manager/metadata/metadata_manager.py
- src/spaceone/inventory/model/google_cloud.py
- src/spaceone/inventory/model/server.py
- src/spaceone/inventory/service/collector_service.py
- Add flag that defines VM is Instance groups's instance (Managed) for power scheduler controller
- Update labels from List of Dict to Dict(String)
> [CLOUD-4334] Add flag that defines VM is Instance groups's instance (Managed)

- src/spaceone/inventory/manager/collector_manager.py
- src/spaceone/inventory/manager/compute_engine/stackdriver_manager.py
- name
- update stack-driver filter
> Add name for identifier for list on cloud service in key

- src/spaceone/inventory/manager/collector_manager.py
- src/spaceone/inventory/manager/compute_engine/stackdriver_manager.py
- instance_name -> instance_id
> Revert back to monitoring_id

- .github/workflows/CI_master_push.yml
- .github/workflows/CI_release.yml
Add new github action for dev testing/production release
- master push : dev testing docker image for every master push(merge)
- release : production docker image triggered by repo administrator
> feat: add github action(master push/release)

- src/spaceone/inventory/connector/google_cloud_compute_connector.py
- src/spaceone/inventory/manager/collector_manager.py
- src/spaceone/inventory/service/collector_service.py
> refactor: add logger

- .github/PULL_REQUEST_TEMPLATE.md
Pull request template file added
> feature: pull request template

- src/spaceone/inventory/manager/collector_manager.py
- updated region info(new region, continent)
- bug fix region code
> feature: updated region info

- src/spaceone/inventory/manager/collector_manager.py
- Remove blank in service_code(Code compatability)
> fix: remove blank in service_code

- src/spaceone/inventory/manager/collector_manager.py
- src/spaceone/inventory/model/resource.py
- src/spaceone/inventory/service/collector_service.py
- Update param in ErrorResource model
- Modify exception case
> fix: Update ErrorResponseResponse exception case

- src/spaceone/inventory/connector/google_cloud_compute_connector.py
- Remove try/except in connector init
> fix: Remove try/except in connector(init google sdk)

- src/spaceone/inventory/manager/collector_manager.py
- src/spaceone/inventory/service/collector_service.py
- Added debug log
- Some protection code
> fix: Added debug logs

- src/spaceone/inventory/manager/collector_manager.py
- src/spaceone/inventory/manager/compute_engine/security_group_manager.py
> fix: Added debugging code

- src/spaceone/inventory/manager/collector_manager.py
- src/spaceone/inventory/manager/compute_engine/security_group_manager.py
- src/spaceone/inventory/service/collector_service.py
> fix: Added exc_info=True

- src/spaceone/inventory/connector/google_cloud_compute_connector.py
- src/spaceone/inventory/manager/collector_manager.py
> etc: Added debug logs

- src/spaceone/inventory/manager/collector_manager.py
- src/spaceone/inventory/manager/compute_engine/security_group_manager.py
- Add protection code 
- If instances in instance_group is in stopped status, return value does not have item param
> fix: add protection code for processing instancegroup
